export const EVENTS = {
  GET_RECORDS: 'GET_RECORDS',
  DELETE_CHAT: 'DELETE_CHAT',
  UPDATE_CHAT: 'UPDATE_CHAT',
  RENAME_SAVED_CHAT: 'RENAME_SAVED_CHAT',
  DELETE_SAVED_CHAT: 'DELETE_SAVED_CHAT',
  SUPPORT_CHAT_CONVERSATION_CREATED: 'SUPPORT_CHAT_CONVERSATION_CREATED',
};
