export const TEXT = {
  // MOBILE_NUMBER: 'Mobile number',
  // OR: 'or',
  // CONTINUE: 'Continue',
  // CONTINUE_WITH_GOOGLE: 'Continue with Google',
  // CONTINUE_WITH_APPLE: 'Continue with Apple',
  // FIND_MY_ACCOUNT: 'Find my account',
  // CONSENT_MESSAGE:
  //   'By proceeding, you consent to get calls, WhatsApp or SMS/RCS messages, including by automated means, from Uber and its affiliates to the number provided',
  // ASK_EMAIL: "What's your email address?",
  // EMAIL_PLACEHOLDER: 'name@example.com',
  // EMAIL: 'Email',
  // ASK_NAME: "What's your name?",
  // HOW_TO_ADDRESS: 'Let us know how to properly address you',
  // FIRST_NAME: 'First name',
  // LAST_NAME: 'Last name',
  // FIRST_NAME_PLACEHOLDER: 'Enter first name',
  // LAST_NAME_PLACEHOLDER: 'Enter last name',
  // NEXT: 'NEXT',
  // I_AGREE: 'I agree',
  // TERMS_TITLE: 'Accept Uber’s Terms & Review Privacy Notice',
  // TERMS_DESCRIPTION:
  //   'By selecting "I Agree" below, I have reviewed and agree to the Terms of Use and acknowledge the Privacy Notice. I am at least 18 years of age.',
  // AGREE_LABEL: 'I Agree',
  // NEXT_BUTTON: 'Next',

  // OTP_TITLE: 'Welcome back, Sumit.',
  // OTP_INSTRUCTION: 'Enter the 4-digit code sent via SMS at 07814 99984.',
  // CHANGE_NUMBER: 'Changed your mobile number?',
  // RESEND_CODE: 'Resend code via SMS',
  // LOGIN_WITH_PASSWORD: 'Login with password',
  // WELCOME: 'Welcome',
  // ENTER_CODE: 'Enter the 6-digit code sent via SMS at ',

  // Fearless code
  WELCOME_MESSAGE: 'Everything you wish for, ',
  WELCOME_MESSAGE_LIGHT: 'lies on the other side of fear…',
  GET_STARTED: 'Get started',
  LOG_IN: 'Log in',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'forgot',
  CHAT: 'Chat',
  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  LANGUAGE: 'Language',
  MEMBERSHIP_STATUS: 'Membership Status',
  SAVED_CHATS: 'Saved Chats',
  LOG_OUT: 'Logout',
  UNAUTHORIZED_ACCESS: 'Session Expired, Please login again.',
  EDIT_PROFILE: 'Edit Profile',
  UPDATE_PROFILE: 'Update Profile',
  DELETE_ACCOUNT: 'Delete account',
  NEW_PASSWORD: 'New password',
  CURRENT_PASSWORD: 'Current password',
  CONFIRM_PASSWORD: 'Confirm password',
  SELECT_PREFERED_LANGUAGE: 'Select your preferred language to continue.',
  ENGLISH: 'English',
  CONFIRM_LOGOUT: 'Are you sure you want to log out?',
  CANCEL: 'Cancel',
  DELETE_ACCOUNT_TITLE: 'Confirm Account \nDeletion',
  DELETE_ACCOUNT_CONFIRMATION:
    'Are you certain you want to proceed with deleting your account?',
  PASSWORD_CHANGED: 'Password Changed!',
  PASSWORD_CHANGED_SUCCESS: 'Your password has been changed successfully.',
  BACK_TO_LOGIN: 'Back to Login',
  FEARLESS_CODE_ADVISER: 'Fearless Code Advisor',
  FEARLESS_CODE_AGENTS: 'Fearless Code AGENTS',
  HOW_CAN_I_ASSIST: 'How can I assist you today?',
  PROMPT_SUGGESTIONS: 'Prompt Suggestion for you',
  WELCOME_TO_FEARLESS_CODE: 'Welcome TO Fearless Code',
  AGENTS: 'Agents',
  AGENT: 'Agent',
  RESOURCES: 'Resources',
  EXPORT_AS_PDF: 'Export as PDF',
  EDIT_CHAT_NAME: 'Edit Chat Name',
  SAVE: 'Save',
  DELETE: 'Delete',
  RENAME_CHAT: 'Rename Chat',
  OK: 'OK',
  SHOW: 'Show',
  VIEW_CHAT: 'View Chat',
  DELETE_CHAT: 'Delete Chat',
  AGENTS_DISCOVER: 'What would you like to discover today?',
  SELECT_A_TOPIC: 'Selects a topic',
  CAREER: 'Career',
  FINANCES: 'Finances',
  SELF_CONFIDENCE: 'Self-confidence',
  FEARLESS_CODE_RESOURCES: 'Fearless Code RESOURCES',

  // Formik Validations
  PLEASE_ENTER_REQUIRED_FIELDS: 'Please enter the required fields.',
  INVALID_EMAIL: 'Email is invalid',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_MINIMUM_CHAR: 'Password must be at least 8 characters',
  PASSWORD_MAXIMUM_CHAR: 'Password must not exceed 15 characters',
  PASSWORD_CONTAIN_NUM: 'Password must contain at least one number',
  PASSWORD_CONTAIN_CHAR_LOWER:
    'Password must contain at least one lowercase letter',
  PASSWORD_CONTAIN_CHAR_UPPER:
    'Password must contain at least one uppercase letter',
  PASSWORD_CONTAIN_CHAR_SYMBOL:
    'Password must contain at least one special character',
  PASSWORD_MATCH: 'Password should match',
  CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
  FIRST_NAME_REQUIRED: 'First name is required',
  LAST_NAME_REQUIRED: 'Last name is required',
  CONCLUSION_REQUIRED: 'The Conclusion',
  CHARACTER_LIMIT: 'Character limit exceeded',
  MAX_ALLOWED: 'Max 50 characters are allowed.',
  INVALID_INPUT: 'Invalid input',
  MIN_LENGTH: 'Minimum length is 2 characters',
  CONTACT_REQUIRED: 'Contact information is required',
  INVALID_CONTACT: 'Invalid contact number',
  ADDRESS_LINE1_REQUIRED: 'Address line 1 is required',
  ADDRESS_LINE1_MAX_LENGTH: 'Address line 1 exceeds maximum length',
  ADDRESS_LINE2_MAX_LENGTH: 'Address line 2 exceeds maximum length',
  CITY_REQUIRED: 'City is required',
  CITY_MAX_LENGTH: 'City exceeds maximum length',
  STATE_REQUIRED: 'State is required',
  STATE_MAX_LENGTH: 'State exceeds maximum length',
  ZIPCODE_REQUIRED: 'Zipcode is required',
  ZIP_CODE_MIMINUM: 'Zipcode should be at least 4 digits',
  ZIP_CODE_MAXIMUM: 'Zipcode should not exceed 6 digits',
  INVALID_ZIPCODE: 'Invalid Zipcode format',
  COUNTRY_REQUIRED: 'Country is required',
  COUNTRY_MAX_LENGTH: 'Country exceeds maximum length',
  TIMEZONE_REQUIRED: 'Timezone is required',
  DOB_REQUIRED: 'Date of birth is required',
  MIN_AGE_ERROR: 'You must be at least 18 years old',
  LANGUAGE_REQUIRED: 'Language is required',
  NAME_REQUIRED: 'Name is required',
  NAME_CHARACTERS_LIMIT: 'Name must be between 2 and 50 characters',
  NAME_LETTER_FORMAT: 'Name should only contain letters and spaces',
  CARD_REQUIRED: 'Card number is required',
  CARD_FORMAT: 'Card number must be in the format 0000-0000-0000-0000',
  CARD_LENGTH_LIMIT: 'Card number must be exactly 16 digits',
  EXPIRY_REQUIRED: 'Expiry date is required',
  EXPIRY_FORMAT: 'Expiry date must be in MM/YY format',
  EXPIRY_VALIDATE: 'Expiry date must not be in the past',
  CVV_REQUIRED: 'CVV is required',
  CVV_FORMAT: 'CVV must be 3 digits',
  TEXT_REQUIRED: 'Text is required',
  INVALID_FIRST_NAME: 'Invalid first name format',
  INVALID_LAST_NAME: 'Invalid last name format',
  INVALID_EMAIL_FORMAT: 'Invalid email format',
  MIN_CONTACT_LENGTH: 'Contact number must be at least 8 characters long',
  MAX_CONTACT_LENGTH: 'Contact number must not exceed 12 characters',
  AGREE: 'You must be agreed to terms and conditions',
};
