$RNNewArchEnabled = false

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    [
      '-p',
      "require.resolve('#{script}', { paths: [process.argv[1]] })",
      __dir__,
    ]
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported

prepare_react_native_project!

# iOS permissions used by the app
setup_permissions([
  'Camera',
  'Microphone',
  'MediaLibrary',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Notifications',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pods with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
target 'FearlessCode' do
  config = use_native_modules!
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # Fix fmt build issue
        if target.name == 'fmt'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_HEADER_ONLY=1'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end